### ISSUE TITLE
No response from the headset system after exiting the stream.Pico neo 3 OS 5.3.3

### ISSUE THREAD

**Issue by Mapleleaves9** [korejan/ALXR-nightly#3]
After the headset exits the stream, the system's unresponsive interface disappears and only the handle can be moved. The headset can only be restarted by force.How can I solve this problem?

**Comment by korejan** [comment]
Hi, since PUI 5.2, Pico's OpenXR runtime I had a major update/re-write and their OpenXR sdk was also been updated but not backwards compitable with older PUI versions:

![image](https://user-images.githubusercontent.com/64199710/210106039-1b1ca879-278f-4b68-9f10-bfd9b3f87fd6.png)

ALXR is still using the SDK for the previous version so this might be the reasion. I want to upgrade the SDK but I only have PN3-link and it has still not recieved the PUI update (stuck on v4.8).

in the future please post issues [here](https://github.com/korejan/ALVR), this repostiory is only for CI builds.

**Comment by korejan** [comment]
Please check [this](https://github.com/korejan/ALVR/discussions/72), if you're still having issues post it [here](https://github.com/korejan/ALVR/issues)
